@port = 9001
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwidGlwb190b2tlbiI6IkFDQ0VTUyIsInVzdWFyaW9faWQiOjMsImVtcHJlc2FfaWQiOjQsInNlZGVfaWQiOjEsInVzZXJuYW1lIjoibWFyaWEucGVyZXoiLCJyb2xlcyI6WyJNw6lkaWNvIl0sInBlcm1pc29zIjpbIkNhbWJpYXIgZXN0YWRvIGRlIGFkbWlzaW9uIiwiQ29uc3VsdGFyIGFkbWlzaW9uZXMiLCJSZWdpc3RyYXIgYWRtaXNpb24iXSwianRpIjoiM2QyNGI1NzUtYzllNy00YWM2LThiNTUtZjkxNDY4N2UzMmYxIiwiaWF0IjoxNzc3MjkzMTYyLCJleHAiOjE3NzczNzk1NjJ9.nWgFiuImOtFxaajX3KxMaC1jprRkl-gyj5OafQ7aSaZBtLqzeLQRjRcliJfLj3MCwSwrzD8AyEgJZ0AEpnoUkw


@base = http://localhost:{{port}}/api/patients

### Crear paciente a partir de tercero
POST {{base}}
Content-Type: application/json
Authorization: {{token}}

{
  "thirdPartyId": 8,
  "bloodGroupId": 9,
  "rhFactorId": 5,
  "disabilityId": null,
  "attentionGroupId": null,
  "knownAllergies": "Penicilina, aspirina",
  "clinicalObservations": "Paciente hipertenso controlado"
}

###

### Obtener paciente por ID
GET {{base}}/5
Authorization: {{token}}

###

### Obtener paciente por tercero
GET {{base}}/third/8
Authorization: {{token}}

###

### Listar pacientes (paginado)
POST {{base}}/list
Content-Type: application/json
Authorization: {{token}}

{
  "page": 0,
  "size": 10,
  "search": ""
}

###

### Listar pacientes con búsqueda por nombre
POST {{base}}/list
Content-Type: application/json
Authorization: {{token}}

{
  "page": 0,
  "size": 10,
  "search": "García"
}

###

### Actualizar paciente
PUT {{base}}/1
Content-Type: application/json
Authorization: {{token}}

{
  "bloodGroupId": 2,
  "rhFactorId": 2,
  "disabilityId": null,
  "attentionGroupId": 1,
  "knownAllergies": "Penicilina, aspirina, ibuprofeno",
  "clinicalObservations": "Paciente hipertenso controlado. Diabético tipo 2"
}

###

### Toggle activo/inactivo
PATCH {{base}}/1/toggle-active
Authorization: {{token}}
